//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: constants.proto

package GameMsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TASK_CONDITION int32

const (
	TASK_CONDITION_TC_ZERO           TASK_CONDITION = 0
	TASK_CONDITION_GOLD              TASK_CONDITION = 1  //获取金币
	TASK_CONDITION_STAGE             TASK_CONDITION = 2  //完成指定关卡
	TASK_CONDITION_PASS_TIMES        TASK_CONDITION = 3  //累计通关次数
	TASK_CONDITION_COST_GOLD         TASK_CONDITION = 4  //消耗金币
	TASK_CONDITION_DIAMOND           TASK_CONDITION = 5  //消耗钻石
	TASK_CONDITION_STAR              TASK_CONDITION = 6  //获取星星数量
	TASK_CONDITION_LV                TASK_CONDITION = 7  //达到等级
	TASK_CONDITION_EQUIP_CNT         TASK_CONDITION = 8  //获得装备总数量
	TASK_CONDITION_SPECIFIC_EQUIP    TASK_CONDITION = 9  //获得指定品质装备数量
	TASK_CONDITION_HERO_CNT          TASK_CONDITION = 10 //获得英雄数量
	TASK_CONDITION_SPECIFIC_HERO     TASK_CONDITION = 11 //获得指定品质英雄数量
	TASK_CONDITION_SOLIDER_CNT       TASK_CONDITION = 12 //获得军团数量
	TASK_CONDITION_SPECIFIC_SOLIDER  TASK_CONDITION = 13 //获得指定品质军团数量
	TASK_CONDITION_BUILDING_CNT      TASK_CONDITION = 14 //获得建筑数量
	TASK_CONDITION_SPECIFIC_BUILDING TASK_CONDITION = 15 //获得指定品质建筑数量
	TASK_CONDITION_EXPLORE_TIMES     TASK_CONDITION = 16 //探索总数量
	TASK_CONDITION_EXPLORE_AREA      TASK_CONDITION = 17 //探索指定地点数量
)

// Enum value maps for TASK_CONDITION.
var (
	TASK_CONDITION_name = map[int32]string{
		0:  "TC_ZERO",
		1:  "GOLD",
		2:  "STAGE",
		3:  "PASS_TIMES",
		4:  "COST_GOLD",
		5:  "DIAMOND",
		6:  "STAR",
		7:  "LV",
		8:  "EQUIP_CNT",
		9:  "SPECIFIC_EQUIP",
		10: "HERO_CNT",
		11: "SPECIFIC_HERO",
		12: "SOLIDER_CNT",
		13: "SPECIFIC_SOLIDER",
		14: "BUILDING_CNT",
		15: "SPECIFIC_BUILDING",
		16: "EXPLORE_TIMES",
		17: "EXPLORE_AREA",
	}
	TASK_CONDITION_value = map[string]int32{
		"TC_ZERO":           0,
		"GOLD":              1,
		"STAGE":             2,
		"PASS_TIMES":        3,
		"COST_GOLD":         4,
		"DIAMOND":           5,
		"STAR":              6,
		"LV":                7,
		"EQUIP_CNT":         8,
		"SPECIFIC_EQUIP":    9,
		"HERO_CNT":          10,
		"SPECIFIC_HERO":     11,
		"SOLIDER_CNT":       12,
		"SPECIFIC_SOLIDER":  13,
		"BUILDING_CNT":      14,
		"SPECIFIC_BUILDING": 15,
		"EXPLORE_TIMES":     16,
		"EXPLORE_AREA":      17,
	}
)

func (x TASK_CONDITION) Enum() *TASK_CONDITION {
	p := new(TASK_CONDITION)
	*p = x
	return p
}

func (x TASK_CONDITION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TASK_CONDITION) Descriptor() protoreflect.EnumDescriptor {
	return file_constants_proto_enumTypes[0].Descriptor()
}

func (TASK_CONDITION) Type() protoreflect.EnumType {
	return &file_constants_proto_enumTypes[0]
}

func (x TASK_CONDITION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TASK_CONDITION.Descriptor instead.
func (TASK_CONDITION) EnumDescriptor() ([]byte, []int) {
	return file_constants_proto_rawDescGZIP(), []int{0}
}

var File_constants_proto protoreflect.FileDescriptor

var file_constants_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2a, 0xa9, 0x02, 0x0a, 0x0e, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49,
	0x54, 0x49, 0x4f, 0x4e, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x43, 0x5f, 0x5a, 0x45, 0x52, 0x4f, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x4f, 0x4c, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53,
	0x54, 0x41, 0x47, 0x45, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x41, 0x53, 0x53, 0x5f, 0x54,
	0x49, 0x4d, 0x45, 0x53, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x53, 0x54, 0x5f, 0x47,
	0x4f, 0x4c, 0x44, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x49, 0x41, 0x4d, 0x4f, 0x4e, 0x44,
	0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x41, 0x52, 0x10, 0x06, 0x12, 0x06, 0x0a, 0x02,
	0x4c, 0x56, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x43, 0x4e,
	0x54, 0x10, 0x08, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x43, 0x5f,
	0x45, 0x51, 0x55, 0x49, 0x50, 0x10, 0x09, 0x12, 0x0c, 0x0a, 0x08, 0x48, 0x45, 0x52, 0x4f, 0x5f,
	0x43, 0x4e, 0x54, 0x10, 0x0a, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x43, 0x5f, 0x48, 0x45, 0x52, 0x4f, 0x10, 0x0b, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x4f, 0x4c, 0x49,
	0x44, 0x45, 0x52, 0x5f, 0x43, 0x4e, 0x54, 0x10, 0x0c, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x43, 0x5f, 0x53, 0x4f, 0x4c, 0x49, 0x44, 0x45, 0x52, 0x10, 0x0d, 0x12,
	0x10, 0x0a, 0x0c, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x43, 0x4e, 0x54, 0x10,
	0x0e, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x43, 0x5f, 0x42, 0x55,
	0x49, 0x4c, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x0f, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x58, 0x50, 0x4c,
	0x4f, 0x52, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x10, 0x10, 0x12, 0x10, 0x0a, 0x0c, 0x45,
	0x58, 0x50, 0x4c, 0x4f, 0x52, 0x45, 0x5f, 0x41, 0x52, 0x45, 0x41, 0x10, 0x11, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x3b, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_constants_proto_rawDescOnce sync.Once
	file_constants_proto_rawDescData = file_constants_proto_rawDesc
)

func file_constants_proto_rawDescGZIP() []byte {
	file_constants_proto_rawDescOnce.Do(func() {
		file_constants_proto_rawDescData = protoimpl.X.CompressGZIP(file_constants_proto_rawDescData)
	})
	return file_constants_proto_rawDescData
}

var file_constants_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_constants_proto_goTypes = []interface{}{
	(TASK_CONDITION)(0), // 0: TASK_CONDITION
}
var file_constants_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_constants_proto_init() }
func file_constants_proto_init() {
	if File_constants_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_constants_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constants_proto_goTypes,
		DependencyIndexes: file_constants_proto_depIdxs,
		EnumInfos:         file_constants_proto_enumTypes,
	}.Build()
	File_constants_proto = out.File
	file_constants_proto_rawDesc = nil
	file_constants_proto_goTypes = nil
	file_constants_proto_depIdxs = nil
}
